### ISSUE TITLE
Start up screen with logo and project information

### ISSUE THREAD

**Issue by Fuzzy61** [Kasamorra/AEiSy_Roboter#11]

**Comment by Kasamorra** [comment]
Hab eine Funktion startup_screen() als Startbildschirm in graphic_controller.c ergänzt. So wird auf dem LCD der Kursname, unsere Namen und das HS-Logo gezeigt. Bei dem HS-Logo kann es aber sein, dass es noch nicht richtig angezeigt wird, da mit draw_picture() eventuell was noch nicht stimmt. Deshalb habe ich die alte Funktion in draw_picture_maße() umbenannt und wieder auskommentiert. So können wir das Logo erstmal weiterhin anzeigen lassen
