### ISSUE TITLE
Alten TImer4 leer räumen und auf neunen Timer umstellen 

### ISSUE THREAD

**Issue by Fuzzy61** [Kasamorra/AEiSy_Roboter#32]
Alles durchgehen:
CLock enablen 
registerbreite beachten usw.
neue prio define anlegen in priority.h

**Comment by Kasamorra** [comment]
Ich würd vorschlagen wir nehmen einfach TIM7 als neuen Timer, der hat auch 16Bit wie TIM4, und die Konfigurierung übernehmen wir einfach von TIM6

**Comment by Fuzzy61** [comment]
müssten wir im letzten praktikum oder am zusätzlichen termin am mittwoch konfiguriert haben
