### ISSUE TITLE
TIM3_IRQ

### ISSUE THREAD

**Issue by Kasamorra** [Kasamorra/AEiSy_Roboter#4]
GPIO-Pin im IRQ von TIM3 als Output setzen. Wenn der EXTI auf die fallende Flanke reagiert, muss der GPIO wieder als Output-Pin gesetzt werden

**Comment by Fuzzy61** [comment]
sollte fertig sein setzt den counter wert zurück deaktiviert die anderen EXTIs und setzt den GPIO PIN wieder auf output gibt als distance wert 0 zurück können wir darauf überprüfen und brauchen keine Flag, da der Wert nie null sein kann
