### ISSUE TITLE
Counter Logik der Odometer überprüfen

### ISSUE THREAD

**Issue by Kasamorra** [Kasamorra/AEiSy_Roboter#49]
Passt es so wie die Odometer zählen? Zählen beide Seiten in die gleiche Richtung?

**Comment by Kasamorra** [comment]
jap ist gespiegelt -> beide Räder drehen in die gleiche Richtung, aber das eine zählt hoch und das andere runter

**Comment by Kasamorra** [comment]
Das haben wir im Praktikum behoben oder? @Fuzzy61

**Comment by Fuzzy61** [comment]
@Kasamorra ja des haben wir denk ich noch kurz vor schluss gefixed gehabt
