### ISSUE TITLE
Softwarestopp vor Kollission

### ISSUE THREAD

**Issue by Fuzzy61** [Kasamorra/AEiSy_Roboter#52]

**Comment by Kasamorra** [comment]
Implementiert in: EXTI9_5_IRQHandler()

Der EXTI beendet die Distanzmessung eines Ultraschallsensors und speichert den gemessenen Wert. Nach diesem Vorgang wird der gemessene Wert mit kollisions_buffer verglichen. kollisions_buffer ist ein #define, das den Abstand zu einem Objekt beinhaltet bei dem unbedingt gebremst werden soll. Ist var kleiner/gleich kollisions_buffer, so wird gebremst mit drive(FAST_STIOP);
